### ISSUE TITLE
Add reverse voltage proctection

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#10]
![Screenshot from 2022-01-19 21-41-22](https://user-images.githubusercontent.com/28790446/150198228-de2d02a2-2236-4ad6-92d0-a121eaf8fe76.png)

**Comment by 0x6f736f646f** [comment]
- Also don't you need a diode and a resistor at the gate pin?
- What about using a Schottky diode?

![Screenshot from 2022-02-01 11-01-23](https://user-images.githubusercontent.com/28790446/151932273-cfbd159d-97cd-4485-bb9c-d171101cd566.png)

**Comment by SammyOina** [comment]
There's a number of ways to do this and you don't have to have the diode you can see [here](https://components101.com/articles/design-guide-pmos-mosfet-for-reverse-voltage-polarity-protection).
But I'll look into the resistor bit

**Comment by 0x6f736f646f** [comment]
From one of the [references](https://components101.com/articles/design-guide-pmos-mosfet-for-reverse-voltage-polarity-protection) you have sent, "_The 100R resistor is the MOSFET gate resistor connected with the Zener diode. The Zener diode protects the gate from overvoltage_."

**Comment by SammyOina** [comment]
The purpose is to clamp the gate-source voltage to a safe region within VGS max. In the case of the transistor, we're using the max is +- 12V and given there is an external power supply of 5V regulated, there is no reason to assume the voltage will go above 12V so as to damage the FET
you can see the datasheet [here](https://datasheet.lcsc.com/lcsc/1810171817_Alpha---Omega-Semicon-AO3401A_C15127.pdf)

**Comment by 0x6f736f646f** [comment]
> The purpose is to clamp the gate-source voltage to a safe region within VGS max. In the case of the transistor, we're using the max is +- 12V and given there is an external power supply of 5V regulated, there is no reason to assume the voltage will go above 12V so as to damage the FET you can see the datasheet [here](https://datasheet.lcsc.com/lcsc/1810171817_Alpha---Omega-Semicon-AO3401A_C15127.pdf)

Understood. Since we will be getting +5V from the avionics board. Then on the avionics PCB, we can include this

@Mike-Kimani

**Comment by Mike-Kimani** [comment]
> > The purpose is to clamp the gate-source voltage to a safe region within VGS max. In the case of the transistor, we're using the max is +- 12V and given there is an external power supply of 5V regulated, there is no reason to assume the voltage will go above 12V so as to damage the FET you can see the datasheet [here](https://datasheet.lcsc.com/lcsc/1810171817_Alpha---Omega-Semicon-AO3401A_C15127.pdf)
> 
> Understood. Since we will be getting +5V from the avionics board. Then on the avionics PCB, we can include this
> 
> @Mike-Kimani

@0x6f736f646f Yes we will.
