### ISSUE TITLE
PCB antenna

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#14]
# Issue

move the antenna out of the PCB surface

# Demo

![Screenshot from 2022-02-01 11-29-01](https://user-images.githubusercontent.com/28790446/151935872-75d3dd82-3500-40e7-8310-d573078d980c.png)
![Screenshot from 2022-02-01 11-29-31](https://user-images.githubusercontent.com/28790446/151935879-331938b6-6da6-41a7-a6b3-9d83dbbe439c.png)

# Ref
1. Comment on [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6860134286629068800?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6860134286629068800%2C6860348725047496704%29)

**Comment by 0x6f736f646f** [comment]
@shohei and @valNyerere why does the PCB antenna needs to be over air?

**Comment by shohei** [comment]
@0x6f736f646f I checked the PCB design book. The wiring on the surface works as another antenna that interferes with the ESP's antenna. The GND plane even becomes an antenna if the shape has a sharp region. The via holes can also become antennae for the multilayer boards.
