### ISSUE TITLE
Buzzer

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#17]
Checkout the recommended schematic at page 4 [here](https://datasheet.lcsc.com/lcsc/1811141116_Jiangsu-Huaneng-Elec-MLT-7525_C95299.pdf)

**Comment by SammyOina** [comment]
What is your recommendation

**Comment by 0x6f736f646f** [comment]
![Screenshot from 2022-02-04 21-55-13](https://user-images.githubusercontent.com/28790446/153146488-aceaa559-63f6-4ee7-b76d-320edbd47942.png)
