### ISSUE TITLE
Ground holes

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/flight-control-computer#19]
Can we use this `M2 PLATED HOLE WITH MINI HOLES`

![image](https://user-images.githubusercontent.com/28790446/153269401-0095a8cf-a93e-4d61-a8b3-33a54428dec4.png)

![image](https://user-images.githubusercontent.com/28790446/153269435-fe832e1a-ab7c-469d-b29e-ebb90ecc4789.png)

**Comment by SammyOina** [comment]
are there any advantages
