### ISSUE TITLE
Change IMU

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#29]
It is rather expensive @ $7.9 per piece and they are actually 4 in stock

**Comment by 0x6f736f646f** [comment]
Have you considered using the QMI8658C aka C2842151

## Ref
1. [Datasheet](https://datasheet.lcsc.com/lcsc/2108161930_QST-QMI8658C_C2842151.pdf)

**Comment by SammyOina** [comment]
I think considering the rewriting of firmware to support this IMU will mess with the N2 timelines

**Comment by SammyOina** [comment]
> It is rather expensive @ $7.9 per piece and they are actually 4 in stock

This will change

**Comment by SammyOina** [comment]
maybe the ICM-42688-P can replace the MPU 6050 but I'll have a look first

**Comment by 0x6f736f646f** [comment]
> > It is rather expensive @ $7.9 per piece and they are actually 4 in stock
> 
> This will change

When will it change?

**Comment by 0x6f736f646f** [comment]
> I think considering the rewriting of firmware to support this IMU will mess with the N2 timelines

Aren't there libraries?

**Comment by SammyOina** [comment]
> > I think considering the rewriting of firmware to support this IMU will mess with the N2 timelines
> 
> Aren't there libraries?

Haven't seen any

**Comment by 0x6f736f646f** [comment]
Either way your current MPU is out of stock

**Comment by SammyOina** [comment]
> QMI8658C

still workin on it, i'm now considering LSM6DS3TR-C

**Comment by 0x6f736f646f** [comment]
I guess if we are using the `Wire.h` library it doesn't matter what IMU is on the other side of the i2c connection

**Comment by SammyOina** [comment]
I'm connecting with SPI for the higher sampling frequency
