### ISSUE TITLE
Which board is to produce power

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#3]
Is it `Flight control` or `Avionics` board?
Since we can use one outlet then distribute power to each board

**Comment by SammyOina** [comment]
I think its avionics

**Comment by 0x6f736f646f** [comment]
Then your `FC` power sub circuit need to be changed

![Screenshot from 2022-01-19 21-41-22](https://user-images.githubusercontent.com/28790446/150281937-78c18d32-e33e-439d-826d-4ae89d16e856.png)

**Comment by SammyOina** [comment]
What changes

**Comment by 0x6f736f646f** [comment]
Since the power is being distributed by `Avionics`. You can include either use pin headers or connectors to tap into the different voltages, 3.3v, 5v and 7.4v instead of having voltage regulators

**Comment by 0x6f736f646f** [comment]
> I can remove the 7.4v regulator, but I need the 5v regulator as I need the USB connection for ease for ease of debugging in the field

No problem

**Comment by 0x6f736f646f** [comment]
I thought you needed 7.4v for the motor and 5v for the rest of the board or?

I was thinking of this approach

![Screenshot from 2022-01-25 17-31-54](https://user-images.githubusercontent.com/28790446/150998285-27f73698-2376-47e4-87b9-5c0b08626188.png)

**Comment by SammyOina** [comment]
No, The power running the motor doesn't run through the PCB, it goes to the ESC instead cause such high current would not be ideal to run on the flight control PCB

**Comment by 0x6f736f646f** [comment]
> No, The power running the motor doesn't run through the PCB, it goes to the ESC instead cause such high current would not be ideal to run on the flight control PCB

Okay 👍🏿

**Comment by 0x6f736f646f** [comment]
- Also don't you need a diode and a resistor at the gate pin?
- What about using a Schottky diode?

![Screenshot from 2022-02-01 11-01-23](https://user-images.githubusercontent.com/28790446/151932273-cfbd159d-97cd-4485-bb9c-d171101cd566.png)
