### ISSUE TITLE
Connector

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#4]
Add a lipo connector if we will be using one lipo battery?

**Comment by SammyOina** [comment]
Lipo is connected to the ESC which has a LIPO connector. The ESC will then supply the PCB with 5v generated from its Battery eliminator circuit

**Comment by 0x6f736f646f** [comment]
I thought your main power is from the LiPo battery

**Comment by SammyOina** [comment]
The ESC needs LiPo supply not the flight control computer
