### ISSUE TITLE
RXD Led

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#5]
What voltage are the RXD and TXD lines?
Would we need a resistor?

![Screenshot from 2022-01-19 21-42-44](https://user-images.githubusercontent.com/28790446/150196566-2c1e3024-b7d4-4e97-addc-af342e48edca.png)

**Comment by SammyOina** [comment]
I'm not sure about this one

**Comment by 0x6f736f646f** [comment]
@shohei and @Mike-Kimani

**Comment by shohei** [comment]
What is the objective of this serial communication? Is the flight controller communicating with other micro controllers?

**Comment by 0x6f736f646f** [comment]
The objective of the serial communication is to be able to program the board

**Comment by 0x6f736f646f** [comment]
It is communicating with other micro controllers but not via serial

**Comment by SammyOina** [comment]
![image](https://user-images.githubusercontent.com/44265300/151677858-3be0734b-04be-40aa-adb6-34b0af139c89.png)
I have tried a similar approach as in the Arduino mega
see [here](https://www.arduino.cc/en/uploads/Main/arduino-mega2560-schematic.pdf)

**Comment by 0x6f736f646f** [comment]
> ![image](https://user-images.githubusercontent.com/44265300/151677858-3be0734b-04be-40aa-adb6-34b0af139c89.png) I have tried a similar approach as in the Arduino mega see [here](https://www.arduino.cc/en/uploads/Main/arduino-mega2560-schematic.pdf)

Grear 👍🏿

**Comment by Mike-Kimani** [comment]
Good catch @0x6f736f646f .
