### ISSUE TITLE
Decoupling capacitors

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#6]
Add decoupling capacitors to the VCC pins. Just an enhancement to smooth out the power

![Screenshot from 2022-01-19 21-43-28](https://user-images.githubusercontent.com/28790446/150196753-78a57570-3d07-48a6-831a-dcba993257d9.png)

![Screenshot from 2022-01-19 21-48-18](https://user-images.githubusercontent.com/28790446/150196828-585df297-17ed-40dd-84f7-a013ee05c6c5.png)

**Comment by SammyOina** [comment]
we have some on the VR side

**Comment by 0x6f736f646f** [comment]
"They are typically applied to power sources to provide a localized source of instantaneous current and provide isolation of the local circuit from power noise in other areas of the design." by [post](https://www.arrow.com/en/research-and-events/articles/why-decoupling-capacitors-matter)

Those on VR aren't they bulk capacitors?

**Comment by 0x6f736f646f** [comment]
Might there be a reason you are using 100nF on the MPU6050 while the others are 0.1uF?
![Uploading Screenshot from 2022-02-01 11-10-07.png…]()

**Comment by SammyOina** [comment]
simillarly for the mpu 6050

**Comment by 0x6f736f646f** [comment]
What about the 100nF cap on the MPU6050?

**Comment by SammyOina** [comment]
what about it?

**Comment by 0x6f736f646f** [comment]
My suggestion was to use the same size of cap unless stated by the datasheet. In this case, MPU6050 can use 0.1uF unless stated by the datasheet. 

This will reduce the variants of components we have on the board. What do you think?

**Comment by SammyOina** [comment]
Mathematically they are equal, I don't get the issue

**Comment by 0x6f736f646f** [comment]
Yes but they will be different as 100nF is C307331 and 0.1uF is C307416

**Comment by SammyOina** [comment]
ok, I'll switch it then

**Comment by 0x6f736f646f** [comment]
Done by https://github.com/nakujaproject/flight-control-computer/pull/12/commits/82f3980e374aa3844d1cb4faae2ecbc800300b11
