### ISSUE TITLE
Move component connected to 7.4v line near the voltage source

### ISSUE THREAD

**Issue by 0x6f736f646f** [nakujaproject/flight-control-computer#9]
To avoid high voltage lines from running across the board and interfering with the signal quality

![Screenshot from 2022-01-19 22-06-31](https://user-images.githubusercontent.com/28790446/150197862-260766be-34e5-440c-93f0-44afa8e22257.png)
![Screenshot from 2022-01-19 22-06-37](https://user-images.githubusercontent.com/28790446/150197871-e1685e28-5d0a-4b91-9f6f-66d2262a8183.png)

**Comment by SammyOina** [comment]
7.4V net removed
